# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5bfe8c5750f756bd5e6c39c5b01ace4a6e943c7425b41f01e68bb454a03158d937326de93a13ca278c857cca584a862d7139723dc6ae85f4298503f45be8d47

test:
  secret_key_base: f435b309ae5b62f6f58f100cd21ed0b4badeb3a063efad46bc0e982e794924c33ca8eee5792642a67cbfebb64390f32c43c0def02e6a3cd1281054823971e0ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
